"""Section to tool mapping for report generation.

This module defines which functions generate data for each report section.
Each section maps to one or more data-gathering functions from customer_report_builder.

The mapping ensures:
1. Each section has a clear, deterministic data source
2. Sections can be executed independently
3. Execution remains tool-based and deterministic (no LLM in data collection)
"""

from typing import Dict, List, Set

# SECTION_TOOL_MAP: Maps section names to the builder functions that populate them.
# These function names correspond to methods in customer_report_builder.py
SECTION_TOOL_MAP: Dict[str, List[str]] = {
    # Income/salary analysis section
    "income_summary": ["_get_salary_block"],

    # Spending analysis section
    "spending_summary": ["_get_category_overview", "_get_top_merchants"],

    # Monthly cashflow section
    "cashflow_analysis": ["_get_monthly_cashflow"],

    # Savings analysis - uses get_total_income, debit_total, get_cash_flow
    "savings_analysis": ["_get_savings_block"],

    # Risk indicators - uses detect_anomalies, get_income_stability, get_balance_trend
    "risk_indicators": ["_get_risk_indicators_block"],

    # LLM-generated recommendations - no tools, generated by LLM from aggregated data
    "recommendations": [],

    # EMI obligations section
    "emi_obligations": ["_get_emi_block"],

    # Rent payments section
    "rent_payments": ["_get_rent_block"],

    # Utility bills section
    "utility_bills": ["_get_bills_block"],
}

# All available section names
AVAILABLE_SECTIONS: List[str] = list(SECTION_TOOL_MAP.keys())

# Core sections that should always be included when data is available
CORE_SECTIONS: Set[str] = {"income_summary", "spending_summary", "cashflow_analysis"}

# Sections that require LLM generation (not tool-based)
LLM_GENERATED_SECTIONS: Set[str] = {"recommendations"}

# Section display names for PDF/HTML rendering
SECTION_DISPLAY_NAMES: Dict[str, str] = {
    "income_summary": "Income Summary",
    "spending_summary": "Spending Analysis",
    "cashflow_analysis": "Monthly Cash Flow",
    "savings_analysis": "Savings Analysis",
    "risk_indicators": "Risk Indicators",
    "recommendations": "Recommendations",
    "emi_obligations": "EMI Obligations",
    "rent_payments": "Rent Payments",
    "utility_bills": "Utility Bills",
}

# Maps section names to CustomerReport field names for aggregation
SECTION_TO_REPORT_FIELD: Dict[str, List[str]] = {
    "income_summary": ["salary"],
    "spending_summary": ["category_overview", "top_merchants"],
    "cashflow_analysis": ["monthly_cashflow"],
    "savings_analysis": ["savings"],
    "risk_indicators": ["risk_indicators"],
    "recommendations": ["customer_review"],
    "emi_obligations": ["emis"],
    "rent_payments": ["rent"],
    "utility_bills": ["bills"],
}
