Drop table if exists PP_HS_BASE_BNK_1;
Create table PP_HS_BASE_BNK_1 as 
select distinct A.CUST_ID, b.reference_date,
            DR_CR_INDCTOR as DR_CR_INDICATOR, 
            TRAN_DATE,
            TRAN_AMT_IN_AC AS TRAN_AMT,
            TRAN_PARTCLR,
            EXTRACT(year from  tran_date) as YEAR,
            EXTRACT(month from  tran_date) as MONTH,
            year || '_' || month as yr_month,
            prty_name,
	    accnt_num
  from kmbl_dex.bl_vw.fct_liability_txn A
  INNER JOIN SANDBOX.PP_HS_BASE_1 B
  ON (A.TRAN_DATE between LAST_DAY(ADD_MONTHS(B.REFERENCE_DATE,-7)) and LAST_DAY(ADD_MONTHS(B.REFERENCE_DATE,-1)))
  and a.cust_id = b.crn
and a.current_flag = 'Y' and a.del_flag = 'N';

DROP TABLE IF EXISTS PP_HS_BASE_BNK_2merchant;
create temp table PP_HS_BASE_BNK_2merchant as
select *
,CASE when
            tran_partclr ILIKE '%SALARY%' OR
            tran_partclr ILIKE '% SALARY %' OR
            tran_partclr ILIKE '%WAGE%' OR
            tran_partclr ILIKE 'salary%' OR  
            tran_partclr ILIKE 'sal %' OR
            tran_partclr ILIKE '%/salary%' OR
            tran_partclr ILIKE '%/salary' OR
            tran_partclr ILIKE '%/ salary%' OR
            tran_partclr ILIKE '%/ sal %' OR
            tran_partclr ILIKE '%/sal %' OR
            tran_partclr ILIKE '%/ salar%' OR
            tran_partclr ILIKE '%/salar' OR
            tran_partclr ILIKE '%-sal' OR    
            tran_partclr ILIKE '%cognizantsal%' OR
            tran_partclr ILIKE '%salar%' OR
            tran_partclr ILIKE '%payroll%' OR
            tran_partclr ILIKE '%WAGES%' OR
            tran_partclr ILIKE '%BULK DEPOSIT%' OR
            tran_partclr ILIKE  '% INCOME %' or
            tran_partclr ILIKE  'PROFESSIONAL FEE%' or
            tran_partclr ILIKE  'STIPEND%' or
            tran_partclr ILIKE  '%PROFESSIONALFEE%' or
            tran_partclr ILIKE  '%PROFESSIONAL FEE%' or
            tran_partclr ILIKE  '%STIPEND%'
 
        THEN 1 END AS SAL_FLAG
 from PP_HS_BASE_BNK_1;

DROP TABLE IF EXISTS PP_HS_BASE_BNK_3keyword;
create table PP_HS_BASE_BNK_3keyword as
select *, 
    CASE
        when lower(tran_partclr) like '%google india di%' THEN 'google india di'
        when lower(tran_partclr) like '%google india se%' THEN 'google india se'
        when lower(tran_partclr) like '%googleindiadigi%' THEN 'googleindiadigi'
        when lower(tran_partclr) like '%google play%' THEN 'google play'
        when lower(tran_partclr) like '%googleindiaserv%' THEN 'googleindiaserv'
        when lower(tran_partclr) like '%googleindi%' THEN 'googleindi'
        when lower(tran_partclr) like '%googleservis%' THEN 'googleservis'
        when lower(tran_partclr) like '%google india%' THEN 'google india'
        when lower(tran_partclr) like '%googleplay%' THEN 'googleplay'
        when lower(tran_partclr) like '%google pay%' THEN 'google pay'
        when lower(tran_partclr) like '%googlepay%' THEN 'googlepay'
        when lower(tran_partclr) like '%google ads%' THEN 'google ads'
        when lower(tran_partclr) like '%googleads%' THEN 'googleads'
        when lower(tran_partclr) like '%google cloud%' THEN 'google cloud'
        when lower(tran_partclr) like '%googlecloud%' THEN 'googlecloud'
        when lower(tran_partclr) like '%mandateexecute%' AND lower(tran_partclr) like '%google%' THEN 'mandateexecute_google'
        when lower(tran_partclr) like '%youtubegoogle%' THEN 'youtubegoogle'
        when lower(tran_partclr) like '%google youtube%' THEN 'google youtube'
        when lower(tran_partclr) like '%google *youtube%' THEN 'google *youtube'
        when lower(tran_partclr) like '%google workspace%' THEN 'google workspace'
        when lower(tran_partclr) like '%google%' THEN 'google'
        when lower(tran_partclr) like '%dream 11%' THEN 'dream 11'
        when lower(tran_partclr) like '%dream11%' THEN 'dream11'
        when lower(tran_partclr) like '%rummy%' THEN 'rummy'
        when lower(tran_partclr) like '%winzo%' THEN 'winzo'
        when lower(tran_partclr) like '%kubera fantasy%' THEN 'kubera fantasy'
        when lower(tran_partclr) like '%fantasy superma%' THEN 'fantasy superma'
        when lower(tran_partclr) like '%play games fantasy%' THEN 'play games fantasy'
        when lower(tran_partclr) like '%real11 fantasy%' THEN 'real11 fantasy'
        when lower(tran_partclr) like '%gamesys fantasy%' THEN 'gamesys fantasy'
        when lower(tran_partclr) like '%indias fantasy%' THEN 'indias fantasy'
        when lower(tran_partclr) like '%fantasy sp%' THEN 'fantasy sp'
        when lower(tran_partclr) like '%lottery%' and lower(tran_partclr) not like '%mhada%' THEN 'lottery'
        when lower(tran_partclr) like '%my11circle%' THEN 'my11circle'
        when lower(tran_partclr) like '%mobile premier%' THEN 'mobile premier'
        when lower(tran_partclr) like '%wager games%' THEN 'wager games'
        when lower(tran_partclr) like '%mpl gaming%' then 'mpl gaming'
        when lower(tran_partclr) like '%a23games%' then 'a23games'
        when lower(tran_partclr) like '%play2win%' then 'play2win'
        when lower(tran_partclr) like '%ludo supreme%' then 'ludo supreme'
        when lower(tran_partclr) like '%gaming%' then 'gaming'
        when lower(tran_partclr) like '%teen patti%' then 'teen patti'
        when lower(tran_partclr) like '%quiz games%' then 'quiz games'
        when lower(tran_partclr) like '%myteam11%' then 'myteam11'
        when lower(tran_partclr) like '%mpl fantasy%' then 'mpl fantasy'
        when lower(tran_partclr) like '%ballebaazi%' then 'ballebaazi'
        when lower(tran_partclr) like '%playerzpot%' then 'playerzpot'
        when lower(tran_partclr) like '%gamezy%' then 'gamezy'
        when lower(tran_partclr) like '%vision11%' then 'vision11'
        when lower(tran_partclr) like '%11wickets%' then '11wickets'
        when lower(tran_partclr) like '%real11%' then 'real11'
        when lower(tran_partclr) like '%nostrapro%' then 'nostrapro'
        when lower(tran_partclr) like '%sportasy%' then 'sportasy'
        when lower(tran_partclr) like '%batball11%' then 'batball11'
        when lower(tran_partclr) like '%fan2play%' then 'fan2play'
        when lower(tran_partclr) like '%leaguex%' then 'leaguex'
        when lower(tran_partclr) like '%khelchamps%' then 'khelchamps'
        when lower(tran_partclr) like '%betting%' then 'betting'
        when lower(tran_partclr) like '%gambling%' then 'gambling'
        when lower(tran_partclr) like '%casino%' then 'casino'
        when lower(tran_partclr) like '%fantasy sport%' then 'fantasy sport'
        when lower(tran_partclr) like '%fairplay%' then 'fairplay'
        when lower(tran_partclr) like '%1xbet%' then '1xbet'
        when lower(tran_partclr) like '%zupee%' then 'zupee'
        when lower(tran_partclr) like '%howzat%' then 'howzat'
        when lower(tran_partclr) like '%pokerbaazi%' then 'pokerbaazi'
        when lower(tran_partclr) like '%myfab11%' then 'myfab11'
        when lower(tran_partclr) like '%gully champs%' then 'gully champs'
        when lower(tran_partclr) like '%golden fantasy%' then 'golden fantasy'
        when lower(tran_partclr) like '%crickpe%' then 'crickpe'
        when lower(tran_partclr) like '%choic11%' then 'choic11'
        when lower(tran_partclr) like '%vision11%' then 'vision11'
        when lower(tran_partclr) like '%league11%' then 'league11'
        -- when lower(tran_partclr) like '%fantasy sports%' then 'fantasy sports'
        when lower(tran_partclr) like '%pocketludo%' then 'pocketludo'
        when lower(tran_partclr) like '%pocket ludo%' then 'pocket ludo'
        when lower(tran_partclr) like '%wizzo%' then 'wizzo'
        when lower(tran_partclr) like '%paytm first game%' then 'paytm first game'
        when lower(tran_partclr) like '%gamezop%' then 'gamezop'
        when lower(tran_partclr) like '%pokerbaazi%' then 'pokerbaazi'
        when lower(tran_partclr) like '%pokerindiaonlin%' then 'pokerindiaonlin'
        when lower(tran_partclr) like '%pokercircleonli%' then 'pokercircleonli'
        when lower(tran_partclr) like '%cashfreepoker%' then 'cashfreepoker'
        when lower(tran_partclr) like '%jungleepoker%' then 'jungleepoker'
        when lower(tran_partclr) like '%pokerstars%' then 'pokerstars'
        when lower(tran_partclr) like '%zomato%' THEN 'zomato'
        when lower(tran_partclr) like '%swiggy%' THEN 'swiggy'
        when lower(tran_partclr) like '%bikanervala%' THEN 'bikanervala'
        when lower(tran_partclr) like '%bikanerwala%' THEN 'bikanerwala'
        when lower(tran_partclr) like '%dominos pizza%' THEN 'dominos pizza'
        when lower(tran_partclr) like '%dominospizza%' THEN 'dominospizza'
        when lower(tran_partclr) like '%pizza hut%' THEN 'pizza hut'
        when lower(tran_partclr) like '%pizzahut%' THEN 'pizzahut'
        when lower(tran_partclr) like '%pizza%' THEN 'pizza'
        when lower(tran_partclr) like '%faasos%' THEN 'faasos'
        when lower(tran_partclr) like '%havmor ice%' THEN 'havmor ice'
        when lower(tran_partclr) like '%theobroma%' THEN 'theobroma'
        when lower(tran_partclr) like '%mithai%' THEN 'mithai'
        when lower(tran_partclr) like '%sweets%' THEN 'sweets'
        when lower(tran_partclr) like '%dairy%' THEN 'dairy'
        when lower(tran_partclr) like '%coffee%' THEN 'coffee'
        when lower(tran_partclr) like '%momo%' THEN 'momo'
        when lower(tran_partclr) like '%café%' THEN 'café'
        when lower(tran_partclr) like '%wine%' THEN 'wine'
        when lower(tran_partclr) like '%liquor%' THEN 'liquor'
        when lower(tran_partclr) like '%spirits%' THEN 'spirits'
        when lower(tran_partclr) like '%debit card annual fee%' THEN 'debit card annual fee'
        when lower(tran_partclr) like '%processing fee%' THEN 'processing fee'
        when lower(tran_partclr) like '%amazon bill pay%' THEN 'amazon bill pay'
        when lower(tran_partclr) like '%amazon pay%' THEN 'amazon pay'
        when lower(tran_partclr) like '%amazon seller%' THEN 'amazon seller'
        when lower(tran_partclr) like '%amazonseller%' THEN 'amazonseller'
        when lower(tran_partclr) like '%amazon india%' THEN 'amazon india'
        when lower(tran_partclr) like '%amazonindia%' THEN 'amazonindia'
        when lower(tran_partclr) like '%amazon sel%' THEN 'amazon sel'
        when lower(tran_partclr) like '%amazon distribu%' THEN 'amazon distribu'
        when lower(tran_partclr) like '%amazonpayindia%' THEN 'amazonpayindia'
        when lower(tran_partclr) like '%amazon transportation%' THEN 'amazon transportation'
        when lower(tran_partclr) like '%amazon ads%' THEN 'amazon ads'
        when lower(tran_partclr) like '%amazon mktplace%' THEN 'amazon mktplace'
        when lower(tran_partclr) ilike '%flight%' then 'flight'
        when lower(tran_partclr) ilike '%spicejet%' then 'spicejet'
        when lower(tran_partclr) ilike '%spice jet%' then 'spice jet'
        when lower(tran_partclr) ilike '%airindia%' then 'airindia'
        when lower(tran_partclr) ilike '%air india%' then 'air india'
        when lower(tran_partclr) ilike '%air ticket%' then 'air ticket'
        when lower(tran_partclr) ilike '%airticket%' then 'airticket'
        when lower(tran_partclr) ilike '%air travel%' then 'air travel'
        when lower(tran_partclr) ilike '%airtravel%' then 'airtravel'
        when lower(tran_partclr) like '%amazon flights%' THEN 'amazon flights'
        when lower(tran_partclr) like '%amazon prime%' THEN 'amazon prime'
        when lower(tran_partclr) like '%indian railways%' THEN 'indian railways'
        when lower(tran_partclr) like '%indian railway%' THEN 'indian railway'
        when lower(tran_partclr) like '%indianrailways%' THEN 'indianrailways'
        when lower(tran_partclr) like '%railway recruit%' THEN 'railway recruit'
        when lower(tran_partclr) like '%railway%' THEN 'railway'
        when lower(tran_partclr) like '%metro%' THEN 'metro'
        when lower(tran_partclr) like '%irctc%' THEN 'irctc'
        when lower(tran_partclr) like '%gstn%' THEN 'gstn'
        when lower(tran_partclr) like '%gst%' THEN 'gst'
        when lower(tran_partclr) like '%goods and services tax%' THEN 'goods and services tax'
        when lower(tran_partclr) like '%closure int after tax%' THEN 'closure int after tax'
        when lower(tran_partclr) like '%etax%' THEN 'etax'
        when lower(tran_partclr) like '%tax%' AND lower(tran_partclr) NOT like '%taxi%' THEN 'tax'
        when lower(tran_partclr) like '%@ptax%' THEN '@ptax'
        when lower(tran_partclr) like '%flipkart%' THEN 'flipkart'
        when lower(tran_partclr) like '%apple media%' then 'apple media'
        when lower(tran_partclr) like '%applemedia%' then 'applemedia'
        when lower(tran_partclr) like '%apple services%' then 'apple services'
        when lower(tran_partclr) like '%appleservices%' then 'appleservices'
        when lower(tran_partclr) like '%apple hospital%' then 'apple hospital'
        when lower(tran_partclr) like '%myntra%' then 'myntra'
        when lower(tran_partclr) like '%delhivery%' then 'delhivery'
        when lower(tran_partclr) like '%dmart%' then 'dmart'
        when lower(tran_partclr) like '%travel%' then 'travel'
        when lower(tran_partclr) like '%textiles%' then 'textiles'
        when lower(tran_partclr) like '%tiles%' then 'tiles'
        when lower(tran_partclr) like '%logistics%' then 'logistics'
        when lower(tran_partclr) like '%shadowfax%' then 'shadowfax'
        when lower(tran_partclr) like '%pharmacy%' then 'pharmacy'
        when lower(tran_partclr) like '%engineering%' then 'engineering'
        when lower(tran_partclr) like '%xpressbees%' then 'xpressbees'
        when lower(tran_partclr) like '%grofers%' then 'grofers'
        when lower(tran_partclr) like '%bigbasket%' then 'bigbasket'
        when lower(tran_partclr) like '%big basket%' then 'big basket'
        when lower(tran_partclr) like '%school%' then 'school'
        when lower(tran_partclr) like '%cement%' and lower(tran_partclr) not like '%replacement%' then 'cement'
        when lower(tran_partclr) like '%paanshop%' then 'paanshop'
        when lower(tran_partclr) like '%paan shop%' then 'paan shop'
        when lower(tran_partclr) like '%ixigo%' then 'ixigo'
        when lower(tran_partclr) like '%bluedart%' then 'bluedart'
        when lower(tran_partclr) like '%blue dart%' then 'blue dart'
        when lower(tran_partclr) like '%makemytrip%' then 'makemytrip'
        when lower(tran_partclr) like '%make my trip%' then 'make my trip'
        when lower(tran_partclr) like '%stationery%' then 'stationery'
        when lower(tran_partclr) like '%college%' then 'college'
        when lower(tran_partclr) like '%customs duty%' then 'customs duty'
        when lower(tran_partclr) like '%education%' then 'education'
        when lower(tran_partclr) like '%plywood%' then 'plywood'
        when lower(tran_partclr) like '%licious%' and lower(tran_partclr) not like '%moneylicious%' then 'licious'
        when lower(tran_partclr) like '%rent for%' then 'rent for'
        when lower(tran_partclr) like '%ecom express%' then 'ecom express'
        when lower(tran_partclr) like '%supermart%' then 'supermart'
        when lower(tran_partclr) like '%tanishq%' then 'tanishq'
        when lower(tran_partclr) like '%nobroker%' then 'nobroker'
        when lower(tran_partclr) like '%remitly%' then 'remitly'
        when lower(tran_partclr) like '%jiomart%' then 'jiomart'
        when lower(tran_partclr) like '%jio mart%' then 'jio mart'
        when lower(tran_partclr) like '%first cry%' then 'first cry'
        when lower(tran_partclr) like '%firstcry%' then 'firstcry'
        when lower(tran_partclr) like '%payroll%' then 'payroll'
        when lower(tran_partclr) like '%reimbursement%' then 'reimbursement'
        when lower(tran_partclr) like '%ibibo%' then 'ibibo'
        when lower(tran_partclr) like '%bangles%' then 'bangles'
        when lower(tran_partclr) like '%tours and%' then 'tours and'
        when lower(tran_partclr) like '%1mg%' then '1mg'
        when lower(tran_partclr) like '%shiprocket%' then 'shiprocket'
        when lower(tran_partclr) like '%westside%' then 'westside'
        when lower(tran_partclr) like '%decathlon%' then 'decathlon'
        when lower(tran_partclr) like '%dtdc%' then 'dtdc'
        when lower(tran_partclr) like '%foods%' then 'foods'
        when lower(tran_partclr) like '%recharge%' then 'recharge'
        when lower(tran_partclr) like '%star bazar%' then 'star bazar'
        when lower(tran_partclr) like '%star bazaar%' then 'star bazaar'
        when lower(tran_partclr) like '%starbazaar%' then 'starbazaar'
        when lower(tran_partclr) like '%academy%' then 'academy'
        when lower(tran_partclr) like '%reliance smart%' then 'reliance smart'
        when lower(tran_partclr) like '%nps cont%' then 'nps cont'
        when lower(tran_partclr) like '%university%' then 'university'
        when lower(tran_partclr) like '%incentive%' then 'incentive'
        when lower(tran_partclr) like '%laptop%' then 'laptop'
        when lower(tran_partclr) like '%room rent%' then 'room rent'
        when lower(tran_partclr) like '%abhibus%' then 'abhibus'
        when lower(tran_partclr) like '%indigo paints%' then 'indigo paints'
        when lower(tran_partclr) like '%/indigo/%' then '/indigo/'
        when lower(tran_partclr) like '%spencers%' then 'spencers'
        when lower(tran_partclr) like '%donation%' then 'donation'
        when lower(tran_partclr) like '%milkbasket%' then 'milkbasket'
        when lower(tran_partclr) like '%ajio%' then 'ajio'
        when lower(tran_partclr) like '%airbnb%' then 'airbnb'
        when lower(tran_partclr) like '%surya hospital %' then 'surya hospital '
        when lower(tran_partclr) like '%apollo hospital%' then 'apollo hospital'
        when lower(tran_partclr) like '%manima hospital%' then 'manima hospital'
        when lower(tran_partclr) like '%books%' then 'books'
        when lower(tran_partclr) like '%toy%' then 'toy'
        when lower(tran_partclr) like '%stationery%' then 'stationery'
        when lower(tran_partclr) like '%library%' then 'library'
        when lower(tran_partclr) like '%cbse%' then 'cbse'
        when lower(tran_partclr) like '%cambridge%' then 'cambridge'
        when lower(tran_partclr) like '%petrol%' then 'petrol'
        when lower(tran_partclr) like '%petroleum%' then 'petroleum'
        when lower(tran_partclr) like '%diesel%' then 'diesel'
        when lower(tran_partclr) like '% gas%' then  ' gas'
        when lower(tran_partclr) like '%fuel%' then 'fuel'
        when lower(tran_partclr) like '%lpg%' then 'lpg'
        when lower(tran_partclr) like '%cylinder%' then 'cylinder'
        when lower(tran_partclr) like '%cng%' then 'cng'
        when lower(tran_partclr) like '%gasoline%' then 'gasoline'
        when lower(tran_partclr) like '%charging%' then 'charging'
        when lower(tran_partclr) like '%indian oil%' then 'indian oil'
        when lower(tran_partclr) like '%gas station%' then 'gas station'
        when lower(tran_partclr) like '%governanc%' then 'governanc'
        when lower(tran_partclr) like '%govt%' then 'govt'
        when lower(tran_partclr) like '%hotel%' then 'hotel'
        when lower(tran_partclr) like '%oyo rooms%' then 'oyo rooms'
        when lower(tran_partclr) like '%oyo town house%' then 'oyo town house'
        when lower(tran_partclr) like '%oyorooms%' then 'oyorooms'
        when lower(tran_partclr) like '%resort%' then 'resort'
        when lower(tran_partclr) like '%lodge%' then 'lodge'
        when lower(tran_partclr) like '%suites%' then 'suites'
        when lower(tran_partclr) like '%motel%' then 'motel'
        when lower(tran_partclr) like '%guest house%' then 'guest house'
        when lower(tran_partclr) like '%radisson%' then 'radisson'
        when lower(tran_partclr) like '%marriott%' then 'marriott'
        when lower(tran_partclr) like '%novotel%' then 'novotel'
        when lower(tran_partclr) like '%homestay%' then 'homestay'
        when lower(tran_partclr) like '%insurance%' then 'insurance'
        when lower(tran_partclr) like '%pension%' then 'pension'
        when lower(tran_partclr) like '%policy%' then 'policy'
        when lower(tran_partclr) like '%bajaj allianz%' then 'bajaj allianz'
        when lower(tran_partclr) like '%tataaig%' then 'tataaig'
        when lower(tran_partclr) like '%tata aig%' then 'tata aig'
        when lower(tran_partclr) like '%icici prudential%' then 'icici prudential'
        when lower(tran_partclr) like '%iciciprudential%' then 'iciciprudential'
        when lower(tran_partclr) like '%maxlife%' then 'maxlife'
        when lower(tran_partclr) like '%max life%' then 'max life'
        when lower(tran_partclr) like '%tata aia%' then 'tata aia'
        when lower(tran_partclr) like '%tataaia%' then 'tataaia'
        when lower(tran_partclr) like '%assurance%' then 'assurance'
        when lower(tran_partclr) like '%hdfc life%' then 'hdfc life'
        when lower(tran_partclr) like '%hdfclife%' then 'hdfclife'
        when lower(tran_partclr) like '%mediclaim%' then 'mediclaim'
        when lower(tran_partclr) like '%future general%' then 'future general'
        when lower(tran_partclr) like '%india insur%' then 'india insur'
        when lower(tran_partclr) like '%maintenance%' then 'maintenance'
        when lower(tran_partclr) like '%repair%' then 'repair'
        when lower(tran_partclr) like '%cleaning%' then 'cleaning'
        when lower(tran_partclr) like '%laundry%' then 'laundry'
        when lower(tran_partclr) like '%plumbing%' then 'plumbing'
        when lower(tran_partclr) like '%electrician%' then 'electrician'
        when lower(tran_partclr) like '%fish corner%' then 'fish corner'
        when lower(tran_partclr) like '%fish%' then 'fish'
        when lower(tran_partclr) like '%aquarium%' then 'aquarium'
        when lower(tran_partclr) like '%taxi%' then 'taxi'
        when lower(tran_partclr) like '%ola cabs%' then 'ola cabs'
        when lower(tran_partclr) like '%olacabs%' then 'olacabs'
        when lower(tran_partclr) like '%uber india%' then 'uber india'
        when lower(tran_partclr) like '%uberindia%' then 'uberindia'
        when lower(tran_partclr) like '%rickshaw%' then 'rickshaw'
        when lower(tran_partclr) like '%rapido%' then 'rapido'
        when lower(tran_partclr) like '%realty%' then 'realty'
        when lower(tran_partclr) like '%estate%' then 'estate'
        when lower(tran_partclr) like '%property%' then 'property'
        when lower(tran_partclr) like '%restaurant%' then 'restaurant'
        when lower(tran_partclr) like '% tea%' then  ' tea'
        when lower(tran_partclr) like '%starbucks%' then 'starbucks'
        when lower(tran_partclr) like '%restaure%' then 'restaure'
        when lower(tran_partclr) like '%bistro%' then 'bistro'
        when lower(tran_partclr) like '%diner%' then 'diner'
        when lower(tran_partclr) like '%cuisine%' then 'cuisine'
        when lower(tran_partclr) like '%dhaba%' then 'dhaba'
        when lower(tran_partclr) like '%bhojanalaya%' then 'bhojanalaya'
        when lower(tran_partclr) like '%food%' then 'food'
        when lower(tran_partclr) like '%dining%' then 'dining'
        when lower(tran_partclr) like '%eatery%' then 'eatery'
        when lower(tran_partclr) like '%snacks%' then 'snacks'
        when lower(tran_partclr) like '%meals%' then 'meals'
        when lower(tran_partclr) like '%fast food%' then 'fast food'
        when lower(tran_partclr) like '%burger%' then 'burger'
        when lower(tran_partclr) like '%biryani%' then 'biryani'
        when lower(tran_partclr) like '%sports%' then 'sports'
        when lower(tran_partclr) like '%fitness%' then 'fitness'
        when lower(tran_partclr) like '%gym%' then 'gym'
        when lower(tran_partclr) ilike '%medical%' then 'medical'
        when lower(tran_partclr) ilike '%medic%' then 'medic'
        when lower(tran_partclr) ilike '%pharmac%' then 'pharmac'
        when lower(tran_partclr) ilike '%pharma%' then 'pharma'
        when lower(tran_partclr) ilike '%chemist%' then 'chemist'
        when lower(tran_partclr) ilike '%medicos%' then 'medicos'
        when lower(tran_partclr) ilike '%medplus%' then 'medplus'
        when lower(tran_partclr) ilike '%healthcare%' then 'healthcare'
        when lower(tran_partclr) ilike '%drugs%' then 'drugs'
        when lower(tran_partclr) ilike '%pharmeasy%' then 'pharmeasy'
        when lower(tran_partclr) ilike '% rd %' then ' rd '
        when lower(tran_partclr) ilike '%fd %' then 'fd '
        when lower(tran_partclr) ilike '% fd %' then ' fd '
        when lower(tran_partclr) ilike '% nse%' then ' nse'
        when lower(tran_partclr) ilike '%zerodha%' then 'zerodha'
        when lower(tran_partclr) ilike '%motilal oswal%' then 'motilal oswal'
        when lower(tran_partclr) ilike '%angelone%' then 'angelone'
        when lower(tran_partclr) ilike '%angel one%' then 'angel one'
        when lower(tran_partclr) ilike '%savings%' then 'savings'
        when lower(tran_partclr) ilike '%investment%' then 'investment'
        when lower(tran_partclr) ilike '%equity%' then 'equity'
        when lower(tran_partclr) ilike '%securities%' then 'securities'
        when lower(tran_partclr) ilike '%mutual fund%' then 'mutual fund'
        when lower(tran_partclr) ilike '%mutualfund%' then 'mutualfund'
        when lower(tran_partclr) ilike '% mf-%' then ' mf-'
        when lower(tran_partclr) ilike '% mf/%' then ' mf/'
        when lower(tran_partclr) ilike '% mf %' then ' mf '
        when lower(tran_partclr) ilike '% mf' then ' mf '
        when lower(tran_partclr) ilike '%mf %' then 'mf '
        when lower(tran_partclr) ilike '%upstox%' then 'upstox'
        when lower(tran_partclr) ilike '% emi %' then ' emi '
        when lower(tran_partclr) ilike '%blinkit%' then 'blinkit'
        when lower(tran_partclr) ilike '%one 97 communications limit%' then 'one 97 communications limit'
        when lower(tran_partclr) ilike '%shopping%' then 'shopping'
        when lower(tran_partclr) ilike '%sweep%' then 'sweep'
        when lower(tran_partclr) ilike '%tea point%' then 'tea point'
        when lower(tran_partclr) ilike '%india cred%' then 'india cred'
        when lower(tran_partclr) ilike '%/slice/%' then '/slice/'
        when lower(tran_partclr) ilike '%nykaa%' then 'nykaa'
        when lower(tran_partclr) ilike '% café/%' then ' café/'
        when lower(tran_partclr) ilike '%Jar Gold%' then 'Jar Gold'
        when lower(tran_partclr) ilike '%BAJAJ FINANCE L%' then 'BAJAJ FINANCE L'
        when lower(tran_partclr) ilike '%NAVI TECHNOLOGI%' then 'NAVI TECHNOLOGI'
        when lower(tran_partclr) ilike '%PhonePe%' then 'PhonePe'
        when lower(tran_partclr) ilike '%PHONEPE LIMITED PAYMENT AGG%' then 'PHONEPE LIMITED PAYMENT AGG'
        when lower(tran_partclr) ilike '%CRED Club%' then 'CRED Club'
        when lower(tran_partclr) ilike '%/JAR/%' then '/JAR/'
        when lower(tran_partclr) ilike '%EXECUTEMANDATE %' then 'EXECUTEMANDATE '
        when lower(tran_partclr) ilike '%Loan Account Number%' then 'Loan Account Number'
        when lower(tran_partclr) ilike '%/jio/%' then '/jio/'
        when lower(tran_partclr) ilike '%/Airtel/%' then '/Airtel/'
        when lower(tran_partclr) ilike '%ekart%' then 'ekart'
        when lower(tran_partclr) ilike '%Navi Bill Payme%' then 'Navi Bill Payme'
        when lower(tran_partclr) ilike '%Vodafone Idea%' then 'Vodafone Idea'
        when lower(tran_partclr) ilike '%DUMMY NAME%' then 'DUMMY NAME'
        when lower(tran_partclr) ilike '%ONE97COMMU%' then 'ONE97COMMU'
        when lower(tran_partclr) ilike '%ZEPTO MARKETPLA%' then 'ZEPTO MARKETPLA'
        when lower(tran_partclr) ilike '%XXXPGN KOTAK 81%' then 'XXXPGN KOTAK 81'
        when lower(tran_partclr) ilike '%Zepto%' then 'Zepto'
        when lower(tran_partclr) ilike '%Meesho%' then 'Meesho'
        when lower(tran_partclr) ilike '%Jio Prepaid Rec%' then 'Jio Prepaid Rec'
        when lower(tran_partclr) ilike '%MPOKKET FINANCI%' then 'MPOKKET FINANCI'
        when lower(tran_partclr) ilike '%MYJIO%' then 'MYJIO'
        -- when lower(tran_partclr) ilike '%MOBIKWIK%' then 'MOBIKWIK'
        when lower(tran_partclr) ilike '%SAFE GOLD%' then 'SAFE GOLD'
        when lower(tran_partclr) ilike '%AVENUE SUPERMAR%' then 'AVENUE SUPERMAR'
        when lower(tran_partclr) ilike '%supermoney%' then 'supermoney'
        when lower(tran_partclr) ilike '%RELIANCE JIO IN%' then 'RELIANCE JIO IN'
        when lower(tran_partclr) ilike '%MPOKKET%' then 'MPOKKET'
        -- when lower(tran_partclr) ilike '%Vi%' then 'Vi'
        when lower(tran_partclr) ilike '%ZEPTONOW%' then 'ZEPTONOW'
        when lower(tran_partclr) ilike '%RELIANCE RETAIL%' then 'RELIANCE RETAIL'
        when lower(tran_partclr) ilike '%KukuFM%' then 'KukuFM'
        when lower(tran_partclr) ilike '%JioHotstar%' then 'JioHotstar'
        when lower(tran_partclr) ilike '%HungerBox%' then 'HungerBox'
        when lower(tran_partclr) ilike '%NETFLIX%' then 'NETFLIX'
        when lower(tran_partclr) ilike '%financial%' then 'financial'
        when lower(tran_partclr) ilike '%airtel%' then 'airtel'
        when lower(tran_partclr) ilike '%fasttag%' then 'fasttag'
        when lower(tran_partclr) ilike '%fastag%' then 'fastag'
        when lower(tran_partclr) ilike '%apollo ph%' then 'apollo ph'
        when lower(tran_partclr) ilike '%tikkiwala%' then 'tikkiwala'
        when lower(tran_partclr) ilike '%dividend%' then 'dividend'
        when lower(tran_partclr) ilike '% retail %' then ' retail '
        when lower(tran_partclr) ilike '%loan repayment%' then 'loan repayment'
        when lower(tran_partclr) ilike '%/slice/%' then '/slice/'
        when lower(tran_partclr) ilike '%aditya birla sun lif%' then 'aditya birla sun lif'
        when lower(tran_partclr) ilike '%central depository services%' then 'central depository services'
        when lower(tran_partclr) ilike '% genral st%' then ' genral st'
        when lower(tran_partclr) ilike '%auto lines%' then 'auto lines'
        when lower(tran_partclr) ilike '% tikki/%' then ' tikki/'
        when lower(tran_partclr) ilike '%cashfree%' then 'cashfree'
        when lower(tran_partclr) ilike '%sharekhan%' then 'sharekhan'
        when lower(tran_partclr) ilike '%lic of india%' then 'lic of india'
        when lower(tran_partclr) ilike '%cinepolis%' then 'cinepolis'
        when lower(tran_partclr) ilike '%reliance industries%' then 'reliance industries'
        when lower(tran_partclr) ilike '%petrochem%' then 'petrochem'
        when lower(tran_partclr) ilike '%niit learning system%' then 'niit learning system'
        when lower(tran_partclr) ilike '% tikki %' then ' tikki '
        when lower(tran_partclr) ilike '%steel%' then 'steel'
        when lower(tran_partclr) ilike '%health plus%' then 'health plus'
        when lower(tran_partclr) ilike '%jalaram store%' then 'jalaram store'
        when lower(tran_partclr) ilike '%tata sky%' then 'tata sky'
        when lower(tran_partclr) ilike '%pocketfm%' then 'pocketfm'
        when lower(tran_partclr) ilike '%reliance retail limi%' then 'reliance retail limi'
        when lower(tran_partclr) ilike '%distributors%' then 'distributors'
        when lower(tran_partclr) ilike '%/w/%' then '/w/'
        when lower(tran_partclr) ilike '%Finance%' then 'Finance'
        when lower(tran_partclr) ilike '%CONTAINER SERVICE%' then 'CONTAINER SERVICE'
        when lower(tran_partclr) ilike '%CONTAINERSERVICE%' then 'CONTAINERSERVICE'
        when lower(tran_partclr) ilike '%ROAD CARRIER%' then 'ROAD CARRIER'
        when lower(tran_partclr) ilike '%ROAD CARR%' then 'ROAD CARR'
        when lower(tran_partclr) ilike '%ROADWAYS%' then 'ROADWAYS'
        when lower(tran_partclr) ilike '%CARGO MOVERS%' then 'CARGO MOVERS'
        when lower(tran_partclr) ilike '%MOVERS%' then 'MOVERS'
        when lower(tran_partclr) ilike '%LOGISTIKS%' then 'LOGISTIKS'
        when lower(tran_partclr) ilike '%TRANS LINK%' then 'TRANS LINK'
        when lower(tran_partclr) ilike '%TRANSLINK%' then 'TRANSLINK'
        when lower(tran_partclr) ilike '%YATAYAT%' then 'YATAYAT'
        when lower(tran_partclr) ilike '%ROAD LINES%' then 'ROAD LINES'
        when lower(tran_partclr) ilike '%ROADLINES%' then 'ROADLINES'
        when lower(tran_partclr) ilike '%TRANSPORT%' then 'TRANSPORT'
        when lower(tran_partclr) ilike '%TRANSP%' then 'TRANSP'
        when lower(tran_partclr) ilike '%cargo%' then 'cargo'
        when lower(tran_partclr) ilike '%vibgyor%' then 'vibgyor'
        when lower(tran_partclr) ilike '%gifts%' then 'gifts'
        when lower(tran_partclr) ilike '%HARDWARE%' then 'HARDWARE'
        when lower(tran_partclr) ilike '%nippon ind%' then 'nippon ind'
        when lower(tran_partclr) ilike '%hdfcmf%' then 'hdfcmf'
        when lower(tran_partclr) ilike '%mirae asset%' then 'mirae asset'
        when lower(tran_partclr) ilike '%small cap%' then 'small cap'
        when lower(tran_partclr) ilike '%smallcap%' then 'smallcap'
        when lower(tran_partclr) ilike '%large cap%' then 'large cap'
        when lower(tran_partclr) ilike '%largecap%' then 'largecap'
        when lower(tran_partclr) ilike '%mutual f%' then 'mutual f'
        when lower(tran_partclr) ilike '%mid cap%' then 'mid cap'
        when lower(tran_partclr) ilike '%midcap%' then 'midcap'
        when lower(tran_partclr) ilike '%nipponmf%' then 'nipponmf'
        when lower(tran_partclr) ilike '%nifty%' then 'nifty'
        when lower(tran_partclr) ilike '%sensex%' then 'sensex'
        when lower(tran_partclr) ilike '%bakers%' then 'bakers'
        when lower(tran_partclr) ilike '%fruits%' then 'fruits'
        when lower(tran_partclr) ilike '%akasa air%' then 'akasa air'
        when lower(tran_partclr) ilike '%bharatgas%' then 'bharatgas'
        when lower(tran_partclr) ilike '%gasventure%' then 'gasventure'
        when lower(tran_partclr) ilike '%chicken%' then 'chicken'
        when lower(tran_partclr) ilike '%rtc/%' then 'rtc/'
        when lower(tran_partclr) ilike '%rtc %' then 'rtc '
        when lower(tran_partclr) ilike '%chefs%' then 'chefs'
        when lower(tran_partclr) ilike '%juicy%' then 'juicy'
        when lower(tran_partclr) ilike '%juice%' then 'juice'
        when lower(tran_partclr) ilike '%sweet%' and lower(tran_partclr) not ilike '%sweety%' then 'sweet'
        when lower(tran_partclr) ilike '%choco%' then 'choco'
        when lower(tran_partclr) ilike '% kabab %' then ' kabab '
        when lower(tran_partclr) ilike '% kebab%' then ' kebab'
        when lower(tran_partclr) ilike '% dosa %' then ' dosa '
        when lower(tran_partclr) ilike '% dosa/%' then ' dosa/'
        when lower(tran_partclr) ilike '% chai/%' then ' chai/'
        when lower(tran_partclr) ilike '% chai %' then ' chai '
        when lower(tran_partclr) ilike '% cake %' then ' cake '
        when lower(tran_partclr) ilike '% cake/%' then ' cake/'
        when lower(tran_partclr) ilike '% chinese %' then ' chinese '
        when lower(tran_partclr) ilike '% chinese/%' then ' chinese/'
        when lower(tran_partclr) ilike '% vej %' then ' vej '
        when lower(tran_partclr) ilike '%/veg %' then '/veg '
        when lower(tran_partclr) ilike '% veg/%' then ' veg/'
        when lower(tran_partclr) ilike '% pan %' then ' pan '
        when lower(tran_partclr) ilike '%pan stol%' then 'pan stol'
        when lower(tran_partclr) ilike '%pan janction%' then 'pan janction'
        when lower(tran_partclr) ilike '%pan palace%' then 'pan palace'
        when lower(tran_partclr) ilike '%pan shop%' then 'pan shop'
        when lower(tran_partclr) ilike '%pan corner%' then 'pan corner'
        when lower(tran_partclr) ilike '%pan parlour%' then 'pan parlour'
        when lower(tran_partclr) ilike '%pan wala%' then 'pan wala'
        when lower(tran_partclr) ilike '%pan sutta%' then 'pan sutta'
        when lower(tran_partclr) ilike '%pan world%' then 'pan world'
        when lower(tran_partclr) ilike '%pan hut%' then 'pan hut'
        when lower(tran_partclr) ilike '%pan store%' then 'pan store'
        when lower(tran_partclr) ilike '%tiffin%' then 'tiffin'
        when lower(tran_partclr) ilike '%tasty%' then 'tasty'
        when lower(tran_partclr) ilike '%saree%' then 'saree'
        when lower(tran_partclr) ilike '%Pets Corner%' then 'Pets Corner'
        when lower(tran_partclr) ilike '%Moolchand Mill%' then 'Moolchand Mill'
        when lower(tran_partclr) ilike '%foot%' then 'foot'
        when lower(tran_partclr) ilike '%pmpml%' then 'pmpml'
        when lower(tran_partclr) ilike '%redbus%' then 'redbus'
        when lower(tran_partclr) ilike '%-mut-%' then '-mut-'
        when lower(tran_partclr) ilike '%smart bazaar%' then 'smart bazaar'
        when lower(tran_partclr) ilike '%billpay for%prepaid%' then 'billpay for%prepaid'
        when lower(tran_partclr) ilike '%billpay for%mf%' then 'billpay for%mf'
        when lower(tran_partclr) ilike '%billpay for%postpaid%' then 'billpay for%postpaid'
        when lower(tran_partclr) ilike '%billpay for bsnl%' then 'billpay for bsnl'
        when lower(tran_partclr) ilike '%billpay for airtel%' then 'billpay for airtel'
        when lower(tran_partclr) ilike '%billpay for%gas%' then 'billpay for%gas'
        when lower(tran_partclr) ilike '%billpay for%elec%' then 'billpay for%elec'
        when lower(tran_partclr) ilike '% super %' then ' super '
        when lower(tran_partclr) ilike '%saloon%' then 'saloon'
        when lower(tran_partclr) ilike '%hair affair%' then 'hair affair'
        when lower(tran_partclr) ilike '%silks%' then 'silks'
        when lower(tran_partclr) ilike '%bakery%' then 'bakery'
        when lower(tran_partclr) ilike '%country delight%' then 'country delight'
        when lower(tran_partclr) ilike '%activa %' then 'activa'
        when lower(tran_partclr) ilike '%indigo airline%' then 'indigo airline'
        when lower(tran_partclr) ilike '% airline%' then 'airline'
        when lower(tran_partclr) ilike '% attire/%' then 'attire'
        when lower(tran_partclr) ilike '%bday' then 'bday'
        when lower(tran_partclr) ilike '%bday %' then 'bday'
        when lower(tran_partclr) ilike '%/bday%' then 'bday'
        when lower(tran_partclr) ilike '% beer %' then 'beer'
        when lower(tran_partclr) ilike '%CC AMEX%' then 'CC AMEX'
        when lower(tran_partclr) ilike '%AMEX CC%' then 'AMEX CC'
        when lower(tran_partclr) ilike '%CC BILL%' then 'CC BILL'
        when lower(tran_partclr) ilike '%AMEX CREDI%' then 'AMEX CREDI'
        when lower(tran_partclr) ilike '%wall clock%' then 'wall clock'
        when lower(tran_partclr) ilike '%cracker%' and lower(tran_partclr) not ilike '%nutcracker%' then 'cracker'
        when lower(tran_partclr) ilike '% Creation/%' then 'Creation'
        when lower(tran_partclr) ilike '% Creations/%' then 'Creation'
        when lower(tran_partclr) ilike '%Electronics%' then 'Electronics'
        when TRAN_PARTCLR  ILIKE '% OWN %' THEN 'OWN'
        when TRAN_PARTCLR  ILIKE '% SELF %' THEN 'SELF'
        when TRAN_PARTCLR  ILIKE '%/SELF %' THEN 'SELF'
        when TRAN_PARTCLR  ILIKE '%/MYSELF%' THEN 'SELF'
        when TRAN_PARTCLR  ILIKE '% MYSELF %' THEN 'SELF'
        when TRAN_PARTCLR ILIKE 'SWEEP %' then 'SWEEP'
        when TRAN_PARTCLR ILIKE '%SWEEP%' then 'SWEEP'
        when TRAN_PARTCLR ILIKE '% SWEEP %' then 'SWEEP'
        when tran_partclr ilike '% loan %' then 'loan'
        when tran_partclr ilike '%/loan%' then 'loan'
        when tran_partclr ilike '%finan%' then 'fin'
        when tran_partclr ilike '%fincap%' then 'fin'
        when tran_partclr ilike '%finser%'  then 'fin'
        when tran_partclr ilike '%LOS PL%' then 'LOS PL'
        when tran_partclr ilike '%LOM PL%' then 'LOM PL'
        when tran_partclr ilike '%WAC PL%' then 'WAC PL'
        when tran_partclr ilike '%PLCC%' then 'PLCC'
        when tran_partclr ilike '%MOBILE BANKING PL%' then 'MOBILE BANKING PL'
        when tran_partclr ilike '%HDFC DISB FUNDED HDFC%' then 'HDFC DISB FUNDED HDFC'
        when tran_partclr ilike '%ICICI BANK LTD RAOG NEFT DISB%' then 'ICICI BANK LTD RAOG NEFT DISB'
        when tran_partclr ilike '%FULLERTON INDIA CREDIT COMP%' then 'FULLERTON INDIA CREDIT COMP'
        when tran_partclr ilike '%RA-LOAN DISBURSEMENT A/C%' then 'RA-LOAN DISBURSEMENT A/C'
        when tran_partclr ilike '%LOAN FROM CLIX%' then 'LOAN FROM CLIX'
        when tran_partclr ilike '%PL DISBURSEMENT SUSP%' then 'PL DISBURSEMENT SUSP'
        when tran_partclr ilike '%RA DISBURSEMENT A/C%' then 'RA DISBURSEMENT A/C'
        when tran_partclr ilike '%MYLOANCARE VENTURES%' then 'MYLOANCARE VENTURES'
        when tran_partclr ilike '%DISB%' then 'DISB'
        when lower(tran_partclr) ilike '%FININVEST%' then 'FININVEST'
        when lower(tran_partclr) ilike '%/groww%' then 'groww'
        when lower(tran_partclr) ilike '%invest%' and lower(tran_partclr) not ilike '%investig%' then 'invest'
        when lower(tran_partclr) ilike '%asset%' then 'asset'
        when lower(tran_partclr) ilike '% nps %' then 'nps'
        when lower(tran_partclr) ilike '%:nps %' then 'nps'
        when lower(tran_partclr) ilike '%blackrock m%' then 'blackrock m'
        when lower(tran_partclr) ilike '%sbi funds%' then 'sbi funds'
        when lower(tran_partclr) ilike '%EDELWEISS%' then 'EDELWEISS'
        when lower(tran_partclr) ilike '%gold etf%' then 'gold etf'
        when lower(tran_partclr) ilike '%:sip %' then 'sip'
        when lower(tran_partclr) ilike '%recruitment%' then 'recruitment'
        when lower(tran_partclr) ilike '%ins debit%' then 'ins debit'
        when lower(tran_partclr) ilike '%limi%' then 'limi'
        when lower(tran_partclr) ilike '%limited%' then 'limited'
        when lower(tran_partclr) ilike '%ltd.%' then 'ltd.'
    END AS KEYWORD
    -- ,case when difference(pp_merchant_2,prty_name) = 4 then 1 else 0 end as self_transfer_flag
from PP_HS_BASE_BNK_2merchant;

drop table if exists SANDBOX.PP_HS_BASE_BNK_4category;
create table SANDBOX.PP_HS_BASE_BNK_4category as
select a.*, 
case when a.sal_flag = 1 then 'Salary'
--    when a.self_transfer_flag = 1 then 'Self_Transfer' 
    else b.category end as category
from PP_HS_BASE_BNK_3keyword a
left join (select distinct* from SANDBOX.PP_KEYWORD_CATEGORY_MAPPING_3) b
on a.keyword = b.keyword;

-- Drop table if exists PP_HS_BASE_BNK_5mcc;
-- Create TEMP table PP_HS_BASE_BNK_5mcc as 
-- select 
-- distinct
-- customeraccount
-- , date(txn_date) as txn_date
-- , amount 
-- , type
-- , customerrefid
-- , remarks
-- , MCCCODE
-- , trantype

--  from kmbl_ipp_dev.public.fct_upi_cbs_txn
-- --  kmbl_dex.srcl_vw.upi_tbl_cbs_tranlog
-- where 
-- date(txn_date) BETWEEN (select min(tran_date) from PP_HS_BASE_BNK_1) and (select max(tran_date) from PP_HS_BASE_BNK_1)
-- and customeraccount in (select distinct accnt_num from PP_HS_BASE_BNK_1);

-- drop table if exists PP_HS_BASE_BNK_6mcc;
-- create temp table PP_HS_BASE_BNK_6mcc as
-- select a.*, b.mcccode, b.trantype 
-- from PP_HS_BASE_BNK_4category a
-- left join PP_HS_BASE_BNK_5mcc b
-- on a.accnt_num = b.customeraccount
-- and (a.tran_partclr ilike 'UPI/%' or a.tran_partclr ilike 'REV-UPI/%')
-- and SPLIT_PART(a.tran_partclr,'/',GREATEST(len(a.tran_partclr) - len(replace(a.tran_partclr,'/','')),1)) = b.customerrefid
-- and a.tran_date = date(b.txn_date)
-- and a.DR_CR_INDICATOR = (case when b.type = 'DEBIT' then 'D' else 'C' end)
-- and a.tran_amt*100 = cast(b.amount as int);

DROP TABLE IF EXISTS SANDBOX.PP_HS_BASE_BNK_output_1;
CREATE TABLE SANDBOX.PP_HS_BASE_BNK_output_1 as
select * from SANDBOX.PP_HS_BASE_BNK_4category;

select * from SANDBOX.PP_HS_BASE_BNK_4category;