
drop table if exists PP_HS_BU_ENQ_tl_1;
create table PP_HS_BU_ENQ_tl_1 as

with sub as (
select a.CRN,a.reference_date,EnquiringMemberShortName,DateofEnquiry,EnquiryPurpose_new,b.report_month
,rank() over(partition by a.crn,a.reference_date order by b.report_month desc) as rank
from  SANDBOX.PP_HS_BASE_BU_1 A
LEFT JOIN kmbl_dex.srcl_vw.ebix_cibil_data_iq b
ON A.CRN = B.CRN AND A.report_month = B.report_month
and upper(b.BASE) in ('ASSET','RL')
)
SELECT * FROM sub
where rank = 1;

drop table if exists PP_HS_BU_ENQ_tl_2;
CREATE TABLE PP_HS_BU_ENQ_tl_2 AS
SELECT *,
    -- Scrub date: last day of previous month
    LAST_DAY(DATEADD(MONTH, -1, TO_DATE(report_month || '01', 'YYYYMMDD'))) AS scrub_date,
 
    -- Onus Flag
    CASE
        WHEN EnquiringMemberShortName = 'KOTAK BANK' THEN 1
        ELSE 0
    END AS ONUS,
 
    -- Account Type CD
    CASE
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN ('AUTO LOAN (PERSONAL)', 'AUTO LOAN') THEN 1
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'HOUSING LOAN' THEN 2
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'PROPERTY LOAN' THEN 3
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN ('LOAN AGAINST SHARES/SECURITIES', 'LOAN AGAINST SHARES / SECURITIES') THEN 4
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'PERSONAL LOAN' THEN 5
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'CONSUMER LOAN' THEN 6
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'GOLD LOAN' THEN 7
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'EDUCATION LOAN' THEN 8
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'LOAN TO PROFESSIONAL' THEN 9
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'CREDIT CARD' THEN 10
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'LEASING' THEN 11
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'OVERDRAFT' THEN 12
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'TWO-WHEELER LOAN' THEN 13
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'NON-FUNDED CREDIT FACILITY' THEN 14
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'LOAN AGAINST BANK DEPOSITS' THEN 15
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'FLEET CARD' THEN 16
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'COMMERCIAL VEHICLE LOAN' THEN 17
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'TELCO - WIRELESS' THEN 18
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'TELCO - BROADBAND' THEN 19
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'TELCO - LANDLINE' THEN 20
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'SELLER FINANCING' THEN 21
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'SELLER FINANCING SOFT (APPLICABLE TO ENQUIRY PURPOSE ONLY)' THEN 22
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'GECL LOAN SECURED' THEN 23
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'GECL LOAN UNSECURED' THEN 24
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'SECURED CREDIT CARD' THEN 31
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'USED CAR LOAN' THEN 32
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'CONSTRUCTION EQUIPMENT LOAN' THEN 33
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'TRACTOR LOAN' THEN 34
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'CORPORATE CREDIT CARD' THEN 35
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'KISAN CREDIT CARD' THEN 36
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'LOAN ON CREDIT CARD' THEN 37
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'PRIME MINISTER JAAN DHAN YOJANA - OVERDRAFT' THEN 38
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'MUDRA LOANS - SHISHU / KISHOR / TARUN' THEN 39
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'MICROFINANCE - BUSINESS LOAN' THEN 40
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'MICROFINANCE - PERSONAL LOAN' THEN 41
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'MICROFINANCE - HOUSING LOAN' THEN 42
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN ('MICROFINANCE - OTHER', 'MICROFINANCE - OTHERS') THEN 43
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'PRADHAN MANTRI AWAS YOJANA - CREDIT LINK SUBSIDY SCHEME MAY CLSS' THEN 44
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'P2P PERSONAL LOAN' THEN 45
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'P2P AUTO LOAN' THEN 46
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'P2P EDUCATION LOAN' THEN 47
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'BUSINESS LOAN - SECURED' THEN 50
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'BUSINESS LOAN - GENERAL' THEN 51
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN ('BUSINESS LOAN - PRIORITY SECTOR - SMALL BUSINESS', 'BLPSSB BUSINESS LOAN -PRIORITY SECTOR - SMALL BUSINESS') THEN 52
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN ('BUSINESS LOAN - PRIORITY SECTOR - AGRICULTURE', 'BLPSAGR BUSINESS LOAN - PRIORITY SECTOR - AGRICULTURE') THEN 53
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN ('BUSINESS LOAN - PRIORITY SECTOR - OTHERS', 'BLPSOTH BUSINESS LOAN - PRIORITY SECTOR - OTHERS') THEN 54
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN ('BUSINESS NON-FUNDED CREDIT FACILITY - GENERAL', 'BNFCFGEN BUSINESS NONFUNDED CREDIT FACILITY - GENERAL') THEN 55
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN (
        'BUSINESS NON-FUNDED CREDIT FACILITY - PRIORITY SECTOR - SMALL BUSINESS',
        'BNFCFPSSB BUSINESS NONFUNDED CREDIT FACILITY - PRIORITY SECTOR - SMALL BUSINESS',
        'BUSINESS NON-FUNDED CREDIT FACILITY-PRIORITY SECTOR- SMALL BUSINESS'
    ) THEN 56
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN (
        'BUSINESS NON-FUNDED CREDIT FACILITY - PRIORITY SECTOR - AGRICULTURE',
        'BNFCFPSAGR BUSINESS NONFUNDED CREDIT FACILITY - PRIORITY SECTOR ?AGRICULTURE',
        'BUSINESS NON-FUNDED CREDIT FACILITY-PRIORITY SECTOR-AGRICULTURE'
    ) THEN 57
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN (
        'BUSINESS NON-FUNDED CREDIT FACILITY - PRIORITY SECTOR-OTHERS',
        'BNFCFPSOTH BUSINESS NONFUNDED CREDIT FACILITY - PRIORITY SECTOROTHERS',
        'BUSINESS NON-FUNDED CREDIT FACILITY-PRIORITY SECTOR-OTHERS'
    ) THEN 58
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN ('BUSINESS LOAN AGAINST BANK DEPOSITS', 'BLABD BUSINESS LOAN AGAINST BANK DEPOSITS') THEN 59
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'BUSINESS LOAN - UNSECURED' THEN 61
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'MICROFINANCE DETAILED REPORT (APPLICABLE TO ENQUIRY PURPOSE ONLY)' THEN 80
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'SUMMARY REPORT (APPLICABLE TO ENQUIRY PURPOSE ONLY)' THEN 81
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'LOCATE PLUS FOR INSURANCE (APPLICABLE TO ENQUIRY PURPOSE ONLY)' THEN 88
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'ACCOUNT REVIEW (APPLICABLE TO ENQUIRY PURPOSE ONLY)' THEN 90
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'RETRO ENQUIRY (APPLICABLE TO ENQUIRY PURPOSE ONLY)' THEN 91
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'LOCATE PLUS (APPLICABLE TO ENQUIRY PURPOSE ONLY)' THEN 92
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'ADVISER LIABILITY (APPLICABLE TO ENQUIRY PURPOSE ONLY)' THEN 97
    WHEN UPPER(ENQUIRYPURPOSE_NEW) IN ('OTHER', '') THEN 0
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'SECURED (ACCOUNT GROUP FOR PORTFOLIO REVIEW RESPONSE)' THEN 98
    WHEN UPPER(ENQUIRYPURPOSE_NEW) = 'UNSECURED (ACCOUNT GROUP FOR PORTFOLIO REVIEW RESPONSE)' THEN 99
    ELSE NULL
END AS ACCOUNT_TYPE_CD
 
FROM PP_HS_BU_ENQ_tl_1;
 
drop table if exists PP_HS_BU_ENQ_tl_3;
CREATE TABLE PP_HS_BU_ENQ_tl_3 AS
SELECT *
    -- Secured/Unsecured Flag
    ,CASE
        WHEN ACCOUNT_TYPE_CD IN (5, 6, 8, 9, 12, 13, 24, 37, 38, 39, 40, 41, 43, 45, 47, 51, 52, 53, 54, 55, 56, 57, 58, 61, 0) THEN 'UNSEC'
        WHEN ACCOUNT_TYPE_CD IN (1, 2, 3, 4, 7, 11, 14, 15, 17, 23, 32, 33, 34, 42, 44, 46, 50, 59) THEN 'SEC'
        ELSE 'OTHERS'
    END AS SEC_UNSEC_FLAG
 
    -- Difference in days and months
    ,DATEDIFF(DAY, DATEOFENQUIRY, scrub_date) AS diff
 
    ,ROUND(DATEDIFF(DAY, DATEOFENQUIRY, scrub_date ) / 30.5, 4) AS diff_month
 
FROM PP_HS_BU_ENQ_tl_2;
 
 
drop table if exists PP_HS_BU_ENQ_tl_4;
create table PP_HS_BU_ENQ_tl_4 as
select crn,reference_date
,sum(case when SEC_UNSEC_FLAG = 'UNSEC' THEN 1 ELSE 0 END) AS enq_unsec_all
,sum(case when SEC_UNSEC_FLAG = 'UNSEC' AND diff_month <= 3 THEN 1 ELSE 0 END) AS enq_unsec_03M
,sum(case when SEC_UNSEC_FLAG = 'UNSEC' AND diff_month <= 6 THEN 1 ELSE 0 END) AS enq_unsec_06M
,sum(case when SEC_UNSEC_FLAG = 'UNSEC' AND diff_month <= 12 THEN 1 ELSE 0 END) AS enq_unsec_12M
,sum(case when SEC_UNSEC_FLAG = 'UNSEC' AND diff_month <= 24 THEN 1 ELSE 0 END) AS enq_unsec_24M
 
from PP_HS_BU_ENQ_tl_3
where DateOfEnquiry <= scrub_date
group by crn,reference_date;

drop table if exists PP_HS_BASE_BU_TL_14;
create table PP_HS_BASE_BU_TL_14 as
select a.*,b.enq_unsec_12M

,case
        when coalesce(b.enq_unsec_24M, 0) <= 0
             and coalesce(a.no_tr_open_l24m_uns_onc, 0) <= 0 then null
        when coalesce(b.enq_unsec_24M, 0) <= 0 then null
        else round(
                (coalesce(a.no_tr_open_l24m_uns_onc, 0)::decimal(18,6)
                 / nullif(b.enq_unsec_24M, 0)::decimal(18,6)),
                4
             ) * 100
    end as tr_to_enq_ratio_uns_l24m
from sandbox.PP_HS_BASE_BU_TL_13 a
left join PP_HS_BU_ENQ_tl_4 b
on a.crn = b.crn AND A.REFERENCE_DATE = B.REFERENCE_DATE;

drop table if exists SANDBOX.PP_HS_BASE_BU_TL_14;
create table SANDBOX.PP_HS_BASE_BU_TL_14 as
SELECT * FROM PP_HS_BASE_BU_TL_14;

SELECT * FROM PP_HS_BASE_BU_TL_14;